services:
  - type: web
    name: vailism-sync-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        value: https://vaibhavanand.codes
    healthCheckPath: /health
